### ISSUE TITLE
S should be uppercase for filename "signatures.txt" in spss.py script

### ISSUE THREAD

**Issue by pwanj** [AlexandrovLab/SigProfilerSingleSample#7]
Hello Mishu,

In the script spss.py, for function single_sample(), in the plotting command, I think the name of the input file should be "Signatures.txt" and not "signatures.txt". 

This is because the file that is output in the results folder is "Signatures.txt". The script looks for file "signatures.txt", and since it is unable to find it, it throws error "SORRY! THE MUTATION CONTEXT YOU PROVIDED COULD NOT BE PLOTTED"

 Line 688       plot.plotSBS(output+"/signatures.txt", output+"/Signature_plot", "", "96", True, custom_text_upper= " ")

I was able to get the signature plot when I ran the same sigplt.plotSBS command using "Signatures.txt" as the input file.

Please let me know if it sounds right. Thank you for your help.

Regards,
Pankhuri

**Comment by mishugeb** [comment]
thanks for mentioning the bug. I will work to solve the bug.

**Comment by pwanj** [comment]
Thank you so much!

Just curious, do you have a timeline for this update?

**Comment by vcsizmok** [comment]
I had the same issue with plotting on Linux, changing 'signatures.txt' to "Signatures.txt' solved the issue. I wonder if @mishugeb is running it in a case insensitive system.

**Comment by mishugeb** [comment]
@vcsizmok, using version 0.0.0.27 should solve the issue.

**Comment by pwanj** [comment]
Hi Mishu,

I got sigproSS v0.0.0.27 installed, but it still did not solve the issue. 

We changed the script ourselves and it worked, as in it stopped giving the Error "SORRY! THE MUTATION CONTEXT YOU PROVIDED COULD NOT BE PLOTTED". 

But now we have another issue. We get error "There may be an issue with the formatting of your matrix file." when running sigproSS. I debugged it, and this error is thrown by  SigProfilerPlotting.

This is very weird because when i ran the same plotSBS command (as in the script) on terminal (python environment), with the same Signatures.txt file (that failed with formatting error), it worked fine and the PDF file was generated.

Do you know what could be the reason for this behaviour. I would appreciate your help.

Thanks
Pankhuri

**Comment by mishugeb** [comment]
Hi Pankhuri,
I am sorry for the problem you faced. I cannot give you a good answer as could not reproduce the error on my side. 
However, please consider that the tool is not completed yet. We are not actively working on tool either for now. Hopefully, the issues with the tool will be solved after three months. Currently, we are trying to finish the SigProfilerExtractor tool.
